version: '3'

services:
  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MARIADB_DATABASE=wordpress
    volumes:
      - ./dbdata/:/var/lib/mysql/
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - db
    image: wordpress:fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    ports:
      - "9000"
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MARIADB_USER
      - WORDPRESS_DB_PASSWORD=$MARIADB_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes:
      - ./wordpress/:/var/www/html/
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    #   - "443:443"
    volumes:
      - ./wordpress/:/var/www/html/
      - ./nginx-conf:/etc/nginx/conf.d
#      - certbot-certs:/etc/letsencrypt
    networks:
      - app-network

#  certbot:
#    depends_on:
#      - webserver
#    image: certbot/certbot
#    container_name: certbot
#    volumes:
#      - certbot-certs:/etc/letsencrypt
#      - wordpress:/var/www/html
#    command: certonly --webroot --webroot-path=/var/www/html --email $CERTBOT_EMAIL --agree-tos --no-eff-email --staging -d example.com -d www.example.com

volumes:
  wordpress:
  dbdata:
#  certbot-certs:

networks:
  app-network:
    driver: bridge